### PR TITLE
strip query params from url before performing actions

### LINKED ISSUE #25: Omit query params from URL before saving in chrome local storage API.
**Is your feature request related to a problem? Please describe.**
Currently if you go to say example.com and save your scroll position. Next time you go to example.com?utm_param=something, then also the page should scroll to the saved position.

Since we are using `window.location.href`, the key generated with and without query params will be different.

**Describe the solution you'd like**

**Additional context**
Useful when you opened a URL which has bunch of tracking parameters.

@prateek3255 I'd love to work on this, if you think this is legit.

### PR DESCRIPTION
**Pull request by itaditya**
- **What does this PR do?**
Omit query params from url before using it in any action. fixes #25 

- **Any background context you want to provide?**
In order to make it work with hash based routers, I have used the command `url.split("?")[0]`. This way we keep the hash but get rid of the query string. Also in scripts where we don't have the window.location object but just have `tab.url` there also this command has to be used.

### CODE REVIEW

**Comment by itaditya** [comment]
@prateek3255 please review the PR

**Comment by prateek3255** [comment]
@itaditya This looks good to me but can you also add a check for `#` in the URLs because many webpages have scroll marks using something like `https://domain.com/contact#form`.

You can use conditional checks by checking if the URL contains `#` or `?` and then stripping accordingly.

**Comment by itaditya** [comment]
If I add a check for hash, then the websites which use hash based routing like
https://design-troopers.surge.sh/#/UI%20Components/Button will break because here the hash doesn't just scroll to a section, it renders a totally different page.

**Comment by prateek3255** [comment]
Makes sense! Okay, I'll test it locally and merge it if it works as expected.

**Comment by itaditya** [comment]
@prateek3255 did you try it out?

**Comment by prateek3255** [comment]
Yeah @itaditya this seems to be working fine, will merge it soon enough and release it in the next version.

**Comment by prateek3255** [comment]
Thanks for contributing @itaditya ✨

**Comment by prateek3255** [comment]
@all-contributors please add itaditya for code

**Comment by itaditya** [comment]
Your welcome @prateek3255. Got to know more about chrome extensions by working on this.

**Pull request merged**
