### PR TITLE
options: added delete & delete-all

### PR DESCRIPTION
**Pull request by underscoreanuj**
- **solved issue #50 **

- **Added both individual delete and delete-all option**

- **Demo**
fina

### CODE REVIEW

**Comment by prateek3255** [comment]
@underscoreanuj This works fine, but the UI looks pretty messed up I think maybe you should use a x icon instead of explicitly creating a delete button. And please take care of the alignment as well.

**Comment by underscoreanuj** [comment]
+ 3 dot hover dropdown to each card which can later be extended to add more options.
+ 0% scroll representation (sometimes the % div would not show up due :

let percentage = Math.round((urls[url].offset / urls[url].total) * 100);

yielding a value of zero.
).

+ "Fetching Saved Scrolls..." / "Empty!!!" / "All Saved Scrolls" automatic switching.

mod_up

**Comment by prateek3255** [comment]
@underscoreanuj Can you move the three dot menu inside the card.

**Comment by underscoreanuj** [comment]
image

**Comment by prateek3255** [comment]
@underscoreanuj I have made some minor style changes and opening the menu on `onclick` instead of hover. Can you please test it from your end as well once and let me know if anything is wrong?

**Comment by prateek3255** [comment]
@all-contributors please add underscoreanuj for code

**Comment by underscoreanuj** [comment]
> @underscoreanuj I have made some minor style changes and opening the menu on `onclick` instead of hover. Can you please pull it and test it from your end as well once and let me know if anything is wrong?

looks great to me.

**Pull request merged**
