### PR TITLE
Adding "About Scrroll In" to the extension

### PR DESCRIPTION
**Pull request by shivanisorte**
- This PR adds a button to the extensions, clicking on which makes a new tab to open from which a user could get information about the extension "Scroll In".

- I have still not added the Twitter and Github link to the buttons in the aboutus.html but have left space for it. Anybody can add the links by putting them into the "" in <a href= "" ...>

- **Screenshots and/or Live Demo**

### CODE REVIEW

**Comment by sharur7** [comment]
@shivanisorte Kindly, please close this PR I am already working on the issue related to it.

**Comment by shivanisorte** [comment]
> @shivanisorte Kindly, please close this PR I am already working on the issue related to it.

@sharur7 , I'm new to Github and this is my first PR. I've already added the feature. I don't see what else is left to work on. I saw an issue and wrote the code for it and opened a PR. Didn't know that the issue was already being solved by the issuer since it wasn't mentioned anywhere. I also remember commenting on the issue that I would work on it. I would be more vigilant and careful henceforth. 
Thankful that I could be of service and help the open source community. :)

**Comment by sharur7** [comment]
> > @shivanisorte Kindly, please close this PR I am already working on the issue related to it.
> 
> @sharur7 , I'm new to Github and this is my first PR. I've already added the feature. I don't see what else is left to work on. I saw an issue and wrote the code for it and opened a PR. Didn't know that the issue was already being solved by the issuer since it wasn't mentioned anywhere. I also remember commenting on the issue that I would work on it. I would be more vigilant and careful henceforth.
> Thankful that I could be of service and help the open source community. :)

As per the Code of Conduct and Contributing Guidelines. Issues are first come, first serve basis. I claimed and created this issue to work on. So, it's better to close this PR to avoid future conflicts. You can start contributing to beginner friendly issues.😄

**Comment by shivanisorte** [comment]
> > > @shivanisorte Kindly, please close this PR I am already working on the issue related to it.
> > 
> > 
> > @sharur7 , I'm new to Github and this is my first PR. I've already added the feature. I don't see what else is left to work on. I saw an issue and wrote the code for it and opened a PR. Didn't know that the issue was already being solved by the issuer since it wasn't mentioned anywhere. I also remember commenting on the issue that I would work on it. I would be more vigilant and careful henceforth.
> > Thankful that I could be of service and help the open source community. :)
> 
> @shivanisorte As per the Code of Conduct and Contributing Guidelines. Issues are first come, first serve basis. I claimed and created this issue to work on. So, it's better to close this PR to avoid future conflicts. You can start contributing to beginner friendly issues.😄

@sharur7 .  I had claimed that I'd be working on it first, but it's alright. There seems to be a misunderstanding. I'm closing the PR. All the best, mate.

**Pull request closed without merging**
